using System.ComponentModel;
using System.Management;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace WinDiagMcpServer.Tools.Wmi;

/// <summary>
/// MCP server tool type for WMI operations.
/// </summary>
// ReSharper disable UnusedMember.Global
[McpServerToolType]
public class McpServerWmiToolType(ILogger<McpServerWmiToolType> logger)
{
    /// <summary>
    /// Executes a WMI query (WQL) and returns the results.
    /// </summary>
    /// <param name="query">The WMI query to execute.</param>
    /// <param name="namespaceName">The WMI namespace.</param>
    /// <returns>A list of dictionaries containing the query results.</returns>
    // [McpServerTool] We remove the tool to force using the diagnosis method
    [Description("Executes a WMI query (WQL) and returns the results.")]
    public List<Dictionary<string, object>> RunWmiQuery(
        [Description("The WMI query to execute (e.g., 'SELECT * FROM Win32_OperatingSystem').")] string query,
        [Description("The WMI namespace (default: 'root\\cimv2').")] string namespaceName = @"root\cimv2")
    {
        var results = new List<Dictionary<string, object>>();
        try
        {
            // Ensure we are running on Windows
            if (!OperatingSystem.IsWindows())
            {
                throw new PlatformNotSupportedException("WMI is only supported on Windows.");
            }

            using var searcher = new ManagementObjectSearcher(namespaceName, query);
            using var collection = searcher.Get();

            foreach (var item in collection)
            {
                var dict = new Dictionary<string, object>();
                foreach (var property in item.Properties)
                {
                    if (property.Value != null)
                    {
                        dict[property.Name] = property.Value;
                    }
                }

                results.Add(dict);
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error executing WMI query: {Query}", query);
            throw new InvalidOperationException($"Error executing WMI query: {ex.Message}", ex);
        }

        return results;
    }

    /// <summary>
    /// Diagnoses a system problem using WMI queries generated by an LLM.
    /// </summary>
    /// <param name="server">The MCP server instance.</param>
    /// <param name="userRequest">A description of the user request.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A diagnosis or recommendation.</returns>
    // ReSharper disable UnusedMember.Global
    [McpServerTool]
    [Description("Query Information and Diagnoses a general system problem utilizing WMI capabilities")]
    public async Task<string> TroubleshootWithWmiAsync(
        McpServer server,
        [Description("A description of the required information or the problem to diagnose.")] string userRequest,
        CancellationToken cancellationToken = default)
    {
        // Step 1: Ask the client (via MCP Sampling) to generate a WMI query.
        // The server is the authority: it provides constraints/examples and retries if the response is invalid.
        const int maxQueryAttempts = 4;

        var basePrompt = $@"
You are a WMI Query Generator.
Your task: derive a single WMI query (WQL) that helps answer the user's request.

USER REQUEST:
{userRequest}

OUTPUT FORMAT (MUST follow):
- Return EXACTLY ONE LINE.
- That line MUST start with SELECT.
- Return ONLY the WMI query (WQL). No prose, no explanations, no prefixes, no markdown, no code fences.

WQL RULES (MUST follow):
1. WQL is NOT SQL.
2. FORBIDDEN: JOIN, UNION, subqueries, CTEs, GROUP BY, HAVING, ORDER BY.
3. Use exactly ONE WMI class in the FROM clause.
4. Prefer selecting specific properties (avoid SELECT * unless necessary).
5. Use simple WHERE filters only.

REFERENCE EXAMPLES (with brief intent):
- Disk free space: SELECT DeviceID, Size, FreeSpace FROM Win32_LogicalDisk WHERE DriveType = 3
- Network adapters: SELECT Name, NetConnectionStatus, Speed FROM Win32_NetworkAdapter WHERE PhysicalAdapter = TRUE
- Non-running services: SELECT Name, State, StartMode FROM Win32_Service WHERE State != ""Running""
- Large-memory processes: SELECT Name, ProcessId, WorkingSetSize FROM Win32_Process WHERE WorkingSetSize > 200000000
";

        string? lastModelText = null;
        string? lastValidationError = null;
        var wmiQuery = string.Empty;

        for (var attempt = 1; attempt <= maxQueryAttempts; attempt++)
        {
            var prompt = basePrompt;
            if (!string.IsNullOrWhiteSpace(lastModelText) && !string.IsNullOrWhiteSpace(lastValidationError))
            {
                prompt += $@"

PREVIOUS OUTPUT (invalid):
{Wql.SanitizeModelOutput(lastModelText)}

WHY INVALID:
{lastValidationError}

Try again. Remember: output EXACTLY ONE LINE that starts with SELECT, and nothing else.
";
            }

            var (queryText, queryError) = await SafeSampleTextAsync(
                server,
                new CreateMessageRequestParams
                {
                    MaxTokens = 180,
                    SystemPrompt = "You generate WQL only. Do not use tools. Do not output prose or markdown.",
                    Messages = [new SamplingMessage { Role = Role.User, Content = [new TextContentBlock { Text = prompt }] }],
                },
                cancellationToken);

            if (string.IsNullOrWhiteSpace(queryText))
            {
                lastModelText = queryText;
                lastValidationError = queryError ?? "Empty sampling response.";
                continue;
            }

            lastModelText = queryText;
            if (Wql.TryValidateAndExtractWql(queryText, out wmiQuery, out var validationError))
            {
                break;
            }

            lastValidationError = validationError;
        }

        if (string.IsNullOrWhiteSpace(wmiQuery))
        {
            return $"Failed to generate a valid WMI query after {maxQueryAttempts} attempts. LastError={lastValidationError}. LastOutput='{Wql.SanitizeModelOutput(lastModelText ?? string.Empty)}'.";
        }

        logger.LogInformation("Generated WMI Query: {Query}", wmiQuery);

        // Step 2: Execute the query
        List<Dictionary<string, object>> queryResults;
        try
        {
            queryResults = RunWmiQuery(wmiQuery);
        }
        catch (Exception ex)
        {
            return $"Failed to execute generated WMI query '{wmiQuery}': {ex.Message}";
        }

        // Step 3: Ask LLM to analyze the results
        var analysisPrompt = $@"
The user reported: ""{userRequest}""
I executed the WMI query: ""{wmiQuery}""
The results are:
{JsonSerializer.Serialize(queryResults, new JsonSerializerOptions { WriteIndented = true })}

Analyze these results and provide a diagnosis or recommendation.
";

        var (analysisText, analysisError) = await SafeSampleTextAsync(
            server,
            new CreateMessageRequestParams
            {
                MaxTokens = 600,
                Messages = [new SamplingMessage { Role = Role.User, Content = [new TextContentBlock { Text = analysisPrompt }] }],
                SystemPrompt = "You are a helpful assistant that analyzes system diagnostics."
            },
            cancellationToken);

        return string.IsNullOrWhiteSpace(analysisText)
            ? $"Failed to generate analysis. {analysisError}"
            : analysisText;
    }

    private static string? ExtractText(CreateMessageResult result)
    {
        if (result.Content.Count == 0)
        {
            return null;
        }

        return string.Concat(result.Content
            .OfType<TextContentBlock>()
            .Select(block => block.Text)
            .Where(text => !string.IsNullOrWhiteSpace(text)));
    }

    private async Task<(string? Text, string? Error)> SafeSampleTextAsync(
        McpServer server,
        CreateMessageRequestParams request,
        CancellationToken cancellationToken)
    {
        try
        {
            var result = await server.SampleAsync(request, cancellationToken);
            var text = ExtractText(result);
            if (string.IsNullOrWhiteSpace(text))
            {
                return (null, "Sampling returned empty content.");
            }

            return (text, null);
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex, "Sampling request failed.");
            return (null, $"Sampling request failed: {ex.GetType().Name}: {ex.Message}");
        }
    }

    private static class Wql
    {
        private static readonly string[] _forbiddenSqlTokens =
        [
            " join ",
            " union ",
            " group by ",
            " having ",
            " order by ",
            " with ",
            " from (",
            " select (",
        ];

        public static string SanitizeModelOutput(string text) => text
            .Replace("```wql", string.Empty, StringComparison.OrdinalIgnoreCase)
            .Replace("```sql", string.Empty, StringComparison.OrdinalIgnoreCase)
            .Replace("```", string.Empty, StringComparison.OrdinalIgnoreCase)
            .Trim();

        public static bool TryValidateAndExtractWql(string? modelText, out string wql, out string validationError)
        {
            wql = string.Empty;
            validationError = string.Empty;

            if (string.IsNullOrWhiteSpace(modelText))
            {
                validationError = "Sampling returned empty text.";
                return false;
            }

            var sanitized = SanitizeModelOutput(modelText);
            var lines = sanitized
                .Split('\n', StringSplitOptions.RemoveEmptyEntries)
                .Select(line => line.Trim())
                .ToArray();

            if (lines.Length != 1)
            {
                validationError = "Output must be EXACTLY ONE LINE.";
                return false;
            }

            var line = lines[0];
            if (!line.StartsWith("SELECT", StringComparison.OrdinalIgnoreCase))
            {
                validationError = "Line must start with SELECT.";
                return false;
            }

            if (line.Contains(';', StringComparison.Ordinal))
            {
                validationError = "Must not include semicolons.";
                return false;
            }

            var lowered = $" {line.ToLowerInvariant()} ";
            if (_forbiddenSqlTokens.Any(token => lowered.Contains(token, StringComparison.Ordinal)))
            {
                validationError = "Contains SQL-only constructs (e.g., JOIN/UNION/GROUP BY/ORDER BY/CTE/subquery).";
                return false;
            }

            wql = line;
            return true;
        }
    }
}
