using System.ComponentModel;
using System.Management;
using System.Text.Json;
using Microsoft.Extensions.Logging;
using ModelContextProtocol.Protocol;
using ModelContextProtocol.Server;

namespace WinDiagMcpServer.Tools.Wmi;

/// <summary>
/// MCP server tool type for WMI operations.
/// </summary>
// ReSharper disable UnusedMember.Global
[McpServerToolType]
public class McpServerWmiToolType(ILogger<McpServerWmiToolType> logger)
{
    /// <summary>
    /// Executes a WMI query (WQL) and returns the results.
    /// </summary>
    /// <param name="query">The WMI query to execute.</param>
    /// <param name="namespaceName">The WMI namespace.</param>
    /// <returns>A list of dictionaries containing the query results.</returns>
    // [McpServerTool] We remove the tool to force using the diagnosis method
    [Description("Executes a WMI query (WQL) and returns the results.")]
    public List<Dictionary<string, object>> RunWmiQuery(
        [Description("The WMI query to execute (e.g., 'SELECT * FROM Win32_OperatingSystem').")] string query,
        [Description("The WMI namespace (default: 'root\\cimv2').")] string namespaceName = @"root\cimv2")
    {
        var results = new List<Dictionary<string, object>>();
        try
        {
            // Ensure we are running on Windows
            if (!OperatingSystem.IsWindows())
            {
                throw new PlatformNotSupportedException("WMI is only supported on Windows.");
            }

            using var searcher = new ManagementObjectSearcher(namespaceName, query);
            using var collection = searcher.Get();

            foreach (var item in collection)
            {
                var dict = new Dictionary<string, object>();
                foreach (var property in item.Properties)
                {
                    if (property.Value != null)
                    {
                        dict[property.Name] = property.Value;
                    }
                }

                results.Add(dict);
            }
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Error executing WMI query: {Query}", query);
            throw new InvalidOperationException($"Error executing WMI query: {ex.Message}", ex);
        }

        return results;
    }

    /// <summary>
    /// Diagnoses a system problem using WMI queries generated by an LLM.
    /// </summary>
    /// <param name="server">The MCP server instance.</param>
    /// <param name="userRequest">A description of the user request.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    /// <returns>A diagnosis or recommendation.</returns>
    // ReSharper disable UnusedMember.Global
    [McpServerTool]
    [Description("Query Information and Diagnoses a general system problem utilizing WMI capabilities")]
    public async Task<string> TroubleshootWithWmiAsync(
        McpServer server,
        [Description("A description of the required information or the problem to diagnose.")] string userRequest,
        CancellationToken cancellationToken = default)
    {
        // Step 1: Ask LLM to generate a WMI query
        var queryPrompt = $@"
You are a Windows system administrator.
The user is asking for an information or reporting a problem using this request: ""{userRequest}""
Generate a single WMI query (WQL) to gather information relevant to this request.
Return ONLY the WMI query string. Do not include any markdown formatting or explanation.
Example: SELECT * FROM Win32_OperatingSystem
";

        var queryResult = await server.SampleAsync(
            new CreateMessageRequestParams
            {
                MaxTokens = 100,
                Messages = [new SamplingMessage { Role = Role.User, Content = [new TextContentBlock { Text = queryPrompt }] }],
                SystemPrompt = "You are a helpful assistant that generates WMI queries.",
                StopSequences = ["\n"]
            },
            cancellationToken);

        var wmiQuery = queryResult.Content.FirstOrDefault() is TextContentBlock textBlock ? textBlock.Text.Trim() : null;

        if (string.IsNullOrWhiteSpace(wmiQuery))
        {
            return "Failed to generate a WMI query.";
        }

        // Clean up the query if it contains markdown code blocks
        wmiQuery = wmiQuery.Replace("```wql", string.Empty).Replace("```sql", string.Empty).Replace("```", string.Empty).Trim();

        logger.LogInformation("Generated WMI Query: {Query}", wmiQuery);

        // Step 2: Execute the query
        List<Dictionary<string, object>> queryResults;
        try
        {
            queryResults = RunWmiQuery(wmiQuery);
        }
        catch (Exception ex)
        {
            return $"Failed to execute generated WMI query '{wmiQuery}': {ex.Message}";
        }

        // Step 3: Ask LLM to analyze the results
        var analysisPrompt = $@"
The user reported: ""{userRequest}""
I executed the WMI query: ""{wmiQuery}""
The results are:
{JsonSerializer.Serialize(queryResults, new JsonSerializerOptions { WriteIndented = true })}

Analyze these results and provide a diagnosis or recommendation.
";

        var analysisResult = await server.SampleAsync(
            new CreateMessageRequestParams
            {
                MaxTokens = 500,
                Messages = [new SamplingMessage { Role = Role.User, Content = [new TextContentBlock { Text = analysisPrompt }] }],
                SystemPrompt = "You are a helpful assistant that analyzes system diagnostics."
            },
            cancellationToken);

        return analysisResult.Content.FirstOrDefault() is TextContentBlock analysisBlock ? analysisBlock.Text : "Failed to generate analysis.";
    }
}
